# Generated by Django 5.0.2 on 2024-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('contrasena', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=9)),
                ('turno', models.CharField(max_length=25)),
                ('rol', models.CharField(default='Trabajador', max_length=10)),
            ],
        ),
    ]
