# Generated by Django 5.0.2 on 2024-05-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0002_menu_mesas_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.FloatField(),
        ),
    ]
